### ISSUE TITLE
No version string

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#42] opened 2019-04-13 14:55 UTC
/gpuowl# make
echo \"`git describe --long --dirty`\" > version.inc
fatal: No names found, cannot describe anything.
echo Version: `cat version.inc`
Version: ""
g++ -Wall -O2 -std=c++17 -Wall Pm1Plan.cpp GmpUtil.cpp Worktodo.cpp common.cpp gpuowl.cpp Gpu.cpp clwrap.cpp Task.cpp checkpoint.cpp timeutil.cpp Args.cpp state.cpp Signal.cpp FFTConfig.cpp -o gpuowl -lOpenCL -lgmp -lstdc++fs -pthread -L/opt/rocm/opencl/lib/x86_64 -L/opt/amdgpu-pro/lib/x86_64-linux-gnu -L/c/Windows/System32 -L.

**Comment by preda** [comment] 2019-04-13 23:36
Yep, this was caused by me not properly pushing the tag; should be fixed now.

**Closed by preda** 2019-04-13 23:36 UTC
