### ISSUE TITLE
Consistent error with ROCm 3.9, AMD Fury X

### ISSUE THREAD

**Issue by baryluk** [preda/gpuowl#203] opened 2020-11-18 19:13 UTC
Hi,

I have no idea if this is issue with gpuowl @ 1a50f1172cf019fe3ce3397b8fdebaace2ed1520 (today's master branch) , or ROCm 3.9.

I had gpuowl with ROCm 3.8 or 3.5, month or two ago, with then master branch, and it was working.

Now it doesn't.

gcc 10.2.0 if that matters.

AMD Radeon R9 Fury X (FIJI, GFX8), 4GB VRAM.

Linux 5.7.6

```
user@debian:~/gpuowl$ ./gpuowl -maxAlloc 3G -prp 96359411 -time 
2020-11-18 19:07:20 GpuOwl VERSION v7.2-16-g1a50f11
2020-11-18 19:07:20 GpuOwl VERSION v7.2-16-g1a50f11
2020-11-18 19:07:20 Note: not found 'config.txt'
2020-11-18 19:07:20 config: -maxAlloc 3G -prp 96359411 -time 
2020-11-18 19:07:20 device 0, unique id ''
2020-11-18 19:07:20 gfx803-0 96359411 FFT: 5M 1K:10:256 (18.38 bpw)
2020-11-18 19:07:20 gfx803-0 96359411 OpenCL args "-DEXP=96359411u -DWIDTH=1024u -DSMALL_HEIGHT=256u -DMIDDLE=10u -DAMDGPU=1 -DMM_CHAIN=1u -DMM2_CHAIN=1u -DMAX_ACCURACY=1 -DWEIGHT_STEP_MINUS_1=0.53783521055865113 -DIWEIGHT_STEP_MINUS_1=-0.3497352686854342 -DIWEIGHTS={0,-0.3497352686854342,-0.15431155841679114,-0.45007863275806081,-0.28481105977256355,-0.069875711887713979,-0.39517297970151255,-0.21340464030762929,-0.48850477977635631,-0.33478539610517538,-0.13486880866361314,-0.4374356983137942,-0.2683685510337061,-0.048491744833292945,-0.38126774011042996,-0.19532046653450927,}  -cl-std=CL2.0 -cl-finite-math-only "
2020-11-18 19:07:23 gfx803-0 96359411 OpenCL compilation in 2.47 s
2020-11-18 19:07:23 gfx803-0 96359411 maxAlloc: 3.0 GB
2020-11-18 19:07:23 gfx803-0 96359411 P1(0) 0 bits
2020-11-18 19:07:23 gfx803-0 96359411 PRP starting from beginning
2020-11-18 19:07:24 gfx803-0 96359411 OK         0 on-load: blockSize 400, 0000000000000003
2020-11-18 19:07:24 gfx803-0 96359411 validating proof residues for power 8
2020-11-18 19:07:24 gfx803-0 96359411 Proof using power 8
2020-11-18 19:07:26 gfx803-0 96359411 EE       800   0.00% 908702a228894e27 1916 us/it + check 0.81s + save 0.00s; ETA 2d 03:17
2020-11-18 19:07:26 gfx803-0 96359411 PRP starting from beginning
2020-11-18 19:07:27 gfx803-0 96359411 OK         0 on-load: blockSize 400, 0000000000000003
2020-11-18 19:07:30 gfx803-0 96359411 EE       800   0.00% 908702a228894e27 1917 us/it + check 0.81s + save 0.00s; ETA 2d 03:18 1 errors
2020-11-18 19:07:30 gfx803-0 96359411 Consistent error 908702a228894e27, will stop.
2020-11-18 19:07:30 gfx803-0 Exiting because "consistent error"
2020-11-18 19:07:30 gfx803-0 Bye
user@debian:~/gpuowl$ 
```

If there are some other tests I can run to check stuff out, please let me know.

Attaching, clinfo and rocminfo

[clinfo.txt](https://github.com/preda/gpuowl/files/5562212/clinfo.txt)
[rocminfo.txt](https://github.com/preda/gpuowl/files/5562213/rocminfo.txt)

**Comment by valeriob01** [comment] 2020-11-20 20:44
suggestion: roll back to ROCm 3.3 which is the fastest I have tested until now.

**Comment by baryluk** [comment] 2020-11-21 14:38
> suggestion: roll back to ROCm 3.3 which is the fastest I have tested until now.

First of, it would be nice if somebody else can verify if their ROCm 3.9 produces same issues or maybe it is just my installation or hardware combination?

**Comment by valeriob01** [comment] 2020-11-22 17:15
starting from version 3.5 there is a nefarious slowdown trend, the fastest version with Radeon VII is 3.3

**Comment by baryluk** [comment] 2020-11-22 20:06
> starting from version 3.5 there is a nefarious slowdown trend, the fastest version with Radeon VII is 3.3

Where did I mention anything about speed? Nowhere. The bug is about consistency error and miscalculation somewhere. Not speed.

As I said, it was working fine for me in ROCm 3.8.

**Comment by valeriob01** [comment] 2020-11-22 20:11
As you will, I never reply to you again. It was only a suggestion, but I see that it is not appreciated.

**Comment by baryluk** [comment] 2020-11-23 02:42
@valeriob01  > As you will, I never reply to you again. It was only a suggestion, but I see that it is not appreciated.

Good, because your suggestion had nothing to do with my reported issue.

**Comment by baryluk** [comment] 2020-11-23 02:52
The first git commit where it started happening is:

```git
commit 084331ec8b5db3a498412225f3aed4c8097ce87d
Author: Mihai Preda <mhpreda@gmail.com>
Date:   Sat Oct 24 21:00:22 2020 +1100

    Fix nSeqErrors (bail out on repeated error)

 Gpu.cpp | 49 +++++++++++++++++++++++++++++--------------------
 1 file changed, 29 insertions(+), 20 deletions(-)
```



Looking at the output from 1 commit before, it looked like this:

```$ ./gpuowl -prp 96359411 -time -maxAlloc 2G
2020-11-23 02:49:45 GpuOwl VERSION v7.1-5-gbcc7cb0
2020-11-23 02:49:45 GpuOwl VERSION v7.1-5-gbcc7cb0
2020-11-23 02:49:45 Note: not found 'config.txt'
2020-11-23 02:49:45 config: -prp 96359411 -time -maxAlloc 2G 
2020-11-23 02:49:45 device 0, unique id ''
2020-11-23 02:49:45 gfx803-0 96359411 FFT: 5M 1K:10:256 (18.38 bpw)
2020-11-23 02:49:45 gfx803-0 96359411 OpenCL args "-DEXP=96359411u -DWIDTH=1024u -DSMALL_HEIGHT=256u -DMIDDLE=10u -DAMDGPU=1 -DCARRY64=1 -DCARRYM64=1 -DMM_CHAIN=1u -DMM2_CHAIN=1u -DMAX_ACCURACY=1 -DWEIGHT_STEP_MINUS_1=0x1.135f22fff92e3p-1 -DIWEIGHT_STEP_MINUS_1=-0x1.662100950bfe7p-2  -cl-unsafe-math-optimizations -cl-std=CL2.0 -cl-finite-math-only "
2020-11-23 02:49:48 gfx803-0 96359411 OpenCL compilation in 2.52 s
2020-11-23 02:49:48 gfx803-0 96359411 maxAlloc: 2.0 GB
2020-11-23 02:49:48 gfx803-0 96359411 P1(0) 0 bits
2020-11-23 02:49:48 gfx803-0 96359411 PRP starting from beginning
2020-11-23 02:49:49 gfx803-0 96359411 OK         0 loaded: blockSize 400, 0000000000000003
2020-11-23 02:49:49 gfx803-0 96359411 validating proof residues for power 8
2020-11-23 02:49:49 gfx803-0 96359411 Proof using power 8
2020-11-23 02:49:51 gfx803-0 96359411 EE       800   0.00% 908702a228894e27 1961 us/it + check 0.84s + save 0.00s; ETA 2d 04:29
2020-11-23 02:49:51 gfx803-0 96359411 PRP starting from beginning
2020-11-23 02:49:52 gfx803-0 96359411 OK         0 loaded: blockSize 400, 0000000000000003
2020-11-23 02:49:55 gfx803-0 96359411 EE       800   0.00% 908702a228894e27 1976 us/it + check 0.84s + save 0.00s; ETA 2d 04:53 1 errors
2020-11-23 02:49:55 gfx803-0 96359411 PRP starting from beginning
2020-11-23 02:49:56 gfx803-0 96359411 OK         0 loaded: blockSize 400, 0000000000000003
2020-11-23 02:49:58 gfx803-0 96359411 EE       800   0.00% 908702a228894e27 1976 us/it + check 0.84s + save 0.00s; ETA 2d 04:53 2 errors
2020-11-23 02:49:58 gfx803-0 96359411 PRP starting from beginning
2020-11-23 02:49:59 gfx803-0 96359411 OK         0 loaded: blockSize 400, 0000000000000003
2020-11-23 02:50:01 gfx803-0 96359411 EE       800   0.00% 908702a228894e27 1976 us/it + check 0.85s + save 0.00s; ETA 2d 04:53 3 errors
2020-11-23 02:50:01 gfx803-0 96359411 PRP starting from beginning
2020-11-23 02:50:02 gfx803-0 96359411 OK         0 loaded: blockSize 400, 0000000000000003
2020-11-23 02:50:05 gfx803-0 96359411 EE       800   0.00% 908702a228894e27 2026 us/it + check 0.85s + save 0.00s; ETA 2d 06:13 4 errors
2020-11-23 02:50:05 gfx803-0 96359411 PRP starting from beginning
2020-11-23 02:50:06 gfx803-0 96359411 OK         0 loaded: blockSize 400, 0000000000000003
2020-11-23 02:50:08 gfx803-0 96359411 EE       800   0.00% 908702a228894e27 1929 us/it + check 0.82s + save 0.00s; ETA 2d 03:38 5 errors
2020-11-23 02:50:08 gfx803-0 96359411 PRP starting from beginning
2020-11-23 02:50:09 gfx803-0 96359411 OK         0 loaded: blockSize 400, 0000000000000003
2020-11-23 02:50:11 gfx803-0 96359411 EE       800   0.00% 908702a228894e27 1930 us/it + check 0.82s + save 0.00s; ETA 2d 03:40 6 errors
2020-11-23 02:50:11 gfx803-0 96359411 PRP starting from beginning
2020-11-23 02:50:12 gfx803-0 96359411 OK         0 loaded: blockSize 400, 0000000000000003
...

```

**Comment by valeriob01** [comment] 2020-11-23 05:03
Remember, once you lose my trust, it is nearly impossible to regain it, and you are not being a nice person. Yours is not a good behavior. I would expect you to appreciate what we say to you, even if it is not what you asked.
Maybe if you only read well what I write you would roll back to a previous version and see if it works.
That said, from my point of view, you are on your own. I will never try to help you again.

**Comment by preda** [comment] 2020-11-23 09:33
> The first git commit where it started happening is:
> commit 084331ec8b5db3a498412225f3aed4c8097ce87d
>[...]
> Looking at the output from 1 commit before, it looked like this:
> 
> ```
> 2020-11-23 02:49:45 GpuOwl VERSION v7.1-5-gbcc7cb0
> 2020-11-23 02:49:45 GpuOwl VERSION v7.1-5-gbcc7cb0
> 2020-11-23 02:49:45 Note: not found 'config.txt'
> 2020-11-23 02:49:45 config: -prp 96359411 -time -maxAlloc 2G 
> 2020-11-23 02:49:45 device 0, unique id ''
> 2020-11-23 02:49:45 gfx803-0 96359411 FFT: 5M 1K:10:256 (18.38 bpw)
> 2020-11-23 02:49:45 gfx803-0 96359411 OpenCL args "-DEXP=96359411u -DWIDTH=1024u -DSMALL_HEIGHT=256u -DMIDDLE=10u -DAMDGPU=1 -DCARRY64=1 -DCARRYM64=1 -DMM_CHAIN=1u -DMM2_CHAIN=1u -DMAX_ACCURACY=1 -DWEIGHT_STEP_MINUS_1=0x1.135f22fff92e3p-1 -DIWEIGHT_STEP_MINUS_1=-0x1.662100950bfe7p-2  -cl-unsafe-math-optimizations -cl-std=CL2.0 -cl-finite-math-only "
> 2020-11-23 02:49:48 gfx803-0 96359411 OpenCL compilation in 2.52 s
> 2020-11-23 02:49:48 gfx803-0 96359411 maxAlloc: 2.0 GB
> 2020-11-23 02:49:48 gfx803-0 96359411 P1(0) 0 bits
> 2020-11-23 02:49:48 gfx803-0 96359411 PRP starting from beginning
> 2020-11-23 02:49:49 gfx803-0 96359411 OK         0 loaded: blockSize 400, 0000000000000003
> 2020-11-23 02:49:49 gfx803-0 96359411 validating proof residues for power 8
> 2020-11-23 02:49:49 gfx803-0 96359411 Proof using power 8
> 2020-11-23 02:49:51 gfx803-0 96359411 EE       800   0.00% 908702a228894e27 1961 us/it + check 0.84s + save 0.00s; ETA 2d 04:29
> 2020-11-23 02:49:51 gfx803-0 96359411 PRP starting from beginning
> 2020-11-23 02:49:52 gfx803-0 96359411 OK         0 loaded: blockSize 400, 0000000000000003
> 2020-11-23 02:49:55 gfx803-0 96359411 EE       800   0.00% 908702a228894e27 1976 us/it + check 0.84s + save 0.00s; ETA 2d 04:53 1 errors
> 2020-11-23 02:49:55 gfx803-0 96359411 PRP starting from beginning
> 2020-11-23 02:49:56 gfx803-0 96359411 OK         0 loaded: blockSize 400, 0000000000000003
> 2020-11-23 02:49:58 gfx803-0 96359411 EE       800   0.00% 908702a228894e27 1976 us/it + check 0.84s + save 0.00s; ETA 2d 04:53 2 errors
> 2020-11-23 02:49:58 gfx803-0 96359411 PRP starting from beginning
> 2020-11-23 02:49:59 gfx803-0 96359411 OK         0 loaded: blockSize 400, 0000000000000003
> 2020-11-23 02:50:01 gfx803-0 96359411 EE       800   0.00% 908702a228894e27 1976 us/it + check 0.85s + save 0.00s; ETA 2d 04:53 3 errors
> 2020-11-23 02:50:01 gfx803-0 96359411 PRP starting from beginning
> 2020-11-23 02:50:02 gfx803-0 96359411 OK         0 loaded: blockSize 400, 0000000000000003
> 2020-11-23 02:50:05 gfx803-0 96359411 EE       800   0.00% 908702a228894e27 2026 us/it + check 0.85s + save 0.00s; ETA 2d 06:13 4 errors
> 2020-11-23 02:50:05 gfx803-0 96359411 PRP starting from beginning
> 2020-11-23 02:50:06 gfx803-0 96359411 OK         0 loaded: blockSize 400, 0000000000000003
> 2020-11-23 02:50:08 gfx803-0 96359411 EE       800   0.00% 908702a228894e27 1929 us/it + check 0.82s + save 0.00s; ETA 2d 03:38 5 errors
> 2020-11-23 02:50:08 gfx803-0 96359411 PRP starting from beginning
> 2020-11-23 02:50:09 gfx803-0 96359411 OK         0 loaded: blockSize 400, 0000000000000003
> 2020-11-23 02:50:11 gfx803-0 96359411 EE       800   0.00% 908702a228894e27 1930 us/it + check 0.82s + save 0.00s; ETA 2d 03:40 6 errors
> 2020-11-23 02:50:11 gfx803-0 96359411 PRP starting from beginning
> 2020-11-23 02:50:12 gfx803-0 96359411 OK         0 loaded: blockSize 400, 0000000000000003
> ```

Thanks for the investigation, but those two cases look the same to me: they both fail with error (EE) at the first check which happens at iteration 800 above. The difference is that "before" it was looping, while "after" it stops because it's hopeless to loop.

But the important thing, that it errors at the first check (EE at 800) is common to "before" and "after".

It is possible that the issue you see is only affecting FuryX.

(I don't have a Fury-family GPU to test, but I've seen similar reports of errors on FuryX).

I think RadeonVII (which is the GPU I use/test on) may not be affected.

You may be able to work-around by increasing the FFT size (with -fft, see -h) which has a speed penalty.

Based on the info available, my first suspicion would be a miscompilation on FuryX. (I'm not ruling out GpuOwl's fault, but at this point it's not my prime candidate).

If it's working with older ROCm (3.8?) that just makes it more likely to be a ROCm regression.

Thanks for the report, sorry I don't have a clearer outcome.

**Comment by baryluk** [comment] 2020-11-23 16:32
@preda Thanks for the response, and verifying it works on your side (with different hardware, but still).

Ok. I will do some tests with different OpenCL versions and different ROCm. Maybe (likely) it is ROCm regression.

**Comment by a-repko** [comment] 2020-11-30 01:49
Hi, I have R9 Nano (same chip as Fury X), which I just tried with ROCm 3.1, 3.9 and AMDGPU-PRO 20.30, all with gpuowl version 635c455 (from 21 Jun 2020; the last one which works with ROCm 3.1). None of the said OpenCL drivers works out-of-the box with gpuowl on R9 Nano for me (EE: similar errors as yours, or zeroed residue "error on load" for AMDGPU-PRO).

However, I just tried option `-use ORIG_SLOWTRIG`, and the calculation indeed seems to work, but only for ROCm. The error persists for AMDGPU-PRO - here the funny thing is that if gpuowl loads a save-file, it shows different interim EE residues with/without ORIG_SLOWTRIG. At the same time, AMDGPU-PRO + gpuowl (and mfakto) works well on Renoir APU (4000-series with Vega 8), which however still doesn't work with ROCm. (By the way, AMDGPU-PRO works well with mfakto on R9 Nano, it is even ca. 8% faster than with ROCm.)

Let me emphasize that (with ROCm) I'm always getting the same residue as you with your exponent, it just one time returns EE, other time (with ORIG_SLOWTRIG), it returns OK (OK persists also in subsequent iterations). So there is probaly something going on in the Gerbicz channel which flags the residue as wrong.

Maybe there is some particular quirk with compilation of gpuowl on GCN3 (Fiji), possibly related to its OpenCL 1.2 compatibility. So, at first, I suggest you to try `-use ORIG_SLOWTRIG` in your setup, to see whether we are seeing the same problem.

**Comment by baryluk** [comment] 2020-12-03 23:22
@a-repko Thanks!

Indeed.

I just tested with ROCm 3.10. Same result as before.

With `-DORIG_SLOWTRIG=1`, it does work correctly. I am getting 2000 us/it.

```
$ ./gpuowl -maxAlloc 3G -prp 96359411 -time -use ORIG_SLOWTRIG
2020-12-03 23:19:55 GpuOwl VERSION v7.2-21-g28dbf88
2020-12-03 23:19:55 GpuOwl VERSION v7.2-21-g28dbf88
2020-12-03 23:19:55 Note: not found 'config.txt'
2020-12-03 23:19:55 config: -maxAlloc 3G -prp 96359411 -time -use ORIG_SLOWTRIG 
2020-12-03 23:19:55 device 0, unique id ''
dlerror: #libMesaOpenCL.so.1: cannot open shared object file: No such file or directory
2020-12-03 23:19:55 gfx803-0 96359411 FFT: 5M 1K:10:256 (18.38 bpw)
2020-12-03 23:19:55 gfx803-0 96359411 OpenCL args "-DEXP=96359411u -DWIDTH=1024u -DSMALL_HEIGHT=256u -DMIDDLE=10u -DAMDGPU=1 -DMM_CHAIN=1u -DMM2_CHAIN=1u -DMAX_ACCURACY=1 -DWEIGHT_STEP_MINUS_1=0.53783521055865113 -DIWEIGHT_STEP_MINUS_1=-0.3497352686854342 -DIWEIGHTS={0,-0.3497352686854342,-0.15431155841679114,-0.45007863275806081,-0.28481105977256355,-0.069875711887713979,-0.39517297970151255,-0.21340464030762929,-0.48850477977635631,-0.33478539610517538,-0.13486880866361314,-0.4374356983137942,-0.2683685510337061,-0.048491744833292945,-0.38126774011042996,-0.19532046653450927,} -DORIG_SLOWTRIG=1  -cl-std=CL2.0 -cl-finite-math-only "
2020-12-03 23:19:58 gfx803-0 96359411 OpenCL compilation in 2.80 s
2020-12-03 23:19:58 gfx803-0 96359411 maxAlloc: 3.0 GB
2020-12-03 23:19:58 gfx803-0 96359411 P1(0) 0 bits
2020-12-03 23:19:58 gfx803-0 96359411 PRP starting from beginning
2020-12-03 23:19:59 gfx803-0 96359411 OK         0 on-load: blockSize 400, 0000000000000003
2020-12-03 23:19:59 gfx803-0 96359411 validating proof residues for power 8
2020-12-03 23:19:59 gfx803-0 96359411 Proof using power 8
2020-12-03 23:20:01 gfx803-0 96359411 OK       800   0.00% 908702a228894e27 1999 us/it + check 0.84s + save 0.11s; ETA 2d 05:31
2020-12-03 23:20:01 gfx803-0 96359411 30.22% carryFused     :    661 us/call x   771 calls
2020-12-03 23:20:01 gfx803-0 96359411 25.97% tailFusedSquare :    548 us/call x   799 calls
2020-12-03 23:20:01 gfx803-0 96359411 20.02% fftMiddleIn    :    393 us/call x   858 calls
2020-12-03 23:20:01 gfx803-0 96359411 18.14% fftMiddleOut   :    369 us/call x   828 calls
2020-12-03 23:20:01 gfx803-0 96359411  1.71% tailFusedMul   :    991 us/call x    29 calls
2020-12-03 23:20:01 gfx803-0 96359411  1.63% fftP           :    316 us/call x    87 calls
2020-12-03 23:20:01 gfx803-0 96359411  1.21% fftW           :    356 us/call x    57 calls
2020-12-03 23:20:01 gfx803-0 96359411  0.80% carryA         :    242 us/call x    56 calls
2020-12-03 23:20:01 gfx803-0 96359411  0.27% carryB         :     81 us/call x    57 calls
2020-12-03 23:20:01 gfx803-0 96359411  0.02% carryM         :    268 us/call x     1 calls
2020-12-03 23:20:01 gfx803-0 96359411 Total time 1.685 s
2020-12-03 23:20:20 gfx803-0 96359411        10000   0.01% 0ba220d1acec321e 1999 us/it
2020-12-03 23:20:40 gfx803-0 96359411        20000   0.02% 7c77b7296427248b 2000 us/it
2020-12-03 23:21:00 gfx803-0 96359411        30000   0.03% a0108bd3ab4fe078 1998 us/it
2020-12-03 23:21:20 gfx803-0 96359411        40000   0.04% decba0aa8101ec48 2002 us/it
2020-12-03 23:21:40 gfx803-0 96359411        50000   0.05% 7fe69bc196899e00 2008 us/it
2020-12-03 23:22:00 gfx803-0 96359411        60000   0.06% d95efc70b7e9c031 2001 us/it
^C
2020-12-03 23:22:02 gfx803-0 96359411 Stopping, please wait..
2020-12-03 23:22:03 gfx803-0 96359411 OK     61200   0.06% 9387504ec88749d8 2000 us/it + check 0.84s + save 0.11s; ETA 2d 05:31
2020-12-03 23:22:03 gfx803-0 96359411 33.39% carryFused     :    661 us/call x 59994 calls
2020-12-03 23:22:03 gfx803-0 96359411 27.68% tailFusedSquare :    548 us/call x 60000 calls
2020-12-03 23:22:03 gfx803-0 96359411 19.95% fftMiddleIn    :    394 us/call x 60156 calls
2020-12-03 23:22:03 gfx803-0 96359411 18.72% fftMiddleOut   :    370 us/call x 60149 calls
2020-12-03 23:22:03 gfx803-0 96359411  0.13% tailFusedMul   :    999 us/call x   149 calls
2020-12-03 23:22:03 gfx803-0 96359411  0.05% fftW           :    362 us/call x   155 calls
2020-12-03 23:22:03 gfx803-0 96359411  0.04% fftP           :    311 us/call x   162 calls
2020-12-03 23:22:03 gfx803-0 96359411  0.03% carryA         :    245 us/call x   155 calls
2020-12-03 23:22:03 gfx803-0 96359411  0.01% carryB         :     86 us/call x   155 calls
2020-12-03 23:22:03 gfx803-0 96359411 Total time 118.792 s
2020-12-03 23:22:03 gfx803-0 Exiting because "stop requested"
2020-12-03 23:22:03 gfx803-0 Bye
```

**Comment by a-repko** [comment] 2020-12-19 22:30
BTW, @valeriob01, I just tried ROCm 3.10 (+ kernel 5.4.80) with gpuowl v6, it seems that they finally fixed it. Now it runs on Raven Ridge again (see RadeonOpenCompute/ROCm#1219), and runs both recent gpuowl and mfakto. Moreover, gpuowl-v6 79ea0cc with ROCm 3.10 is ca. 2% faster than gpuowl fa590e4 with ROCm 3.1. This speed variation was observed on both APU Raven Ridge and Radeon VII. So it seems that we can finally go along with the new versions of ROCm (although I haven't tested 4.0 yet).

off-topic: mfakto is now ca. 2% slower than with 3.1, but can boosted by ca. 8% by using AMDGPU-PRO OpenCL https://gist.github.com/kytulendu/3351b5d0b4f947e19df36b1ea3c95cbe
instead, which however causes some graphics instability. Anyway, it is good to test both GCN3(=GCNF) and GCN5(=GCN) in mfakto.ini for the given GPU + exponent (+ bit-depth) in order to achieve best throughput and/or energy efficiency.

**Comment by selroc** [comment] 2020-12-20 03:24
Thanks, but I am now using ROCm 3.3 with gpuOwl 7.x and Radeon VII, it is fast and smooth.

**Comment by valeriob01** [comment] 2020-12-20 03:46
> Thanks, but I am now using ROCm 3.3 with gpuOwl 7.x and Radeon VII, it is fast and smooth.

sorry, I have replied with my second account.

**Comment by a-repko** [comment] 2021-01-06 19:41
So I again evaluated the speed more carefully with the new ROCm versions on Radeon VII (exponents in 56M and 332M ranges; same background tasks), and I see that gpuowl is indeed slower than with ROCm 3.1; slowdown is 2% for ROCm 3.10, but almost 1% is recovered in 4.0.

However, they seem to have dropped support for gfx803 (Fiji and Polaris) in ROCm 4.0. I currently don't have the card at hand, I will check it later.

**Comment by baryluk** [comment] 2021-01-07 08:13
> However, they seem to have dropped support for gfx803 (Fiji and Polaris) in ROCm 4.0. I currently don't have the card at hand, I will check it later.

Yes, sadly a number of performance and bug reports about my Fiji, got closed due to ROCm 4.0 dropping the support for Fiji. And unfortunately the ROCm is not in great shape in terms of non-AMD contributions. It is there, but not enough to keep gfx8 alive fully. Which is weird a bit, as the AMD Pro drivers for Linux does look working well still with Fiji, as well on Windows. Hope they do better cooperation between Windows and Linux teams, to share their testing, development and QA.

**Comment by a-repko** [comment] 2021-07-14 21:31
@baryluk 
I finally tested my R9 Nano. So it seems that ROCm 4.0 works the same as with older versions, and needs `-use ORIG_SLOWTRIG`. Nevertheless, ROCm 4.2 works flawlessly out-of-the-box (no -use options) with both gpuowl-v6 and mfakto! OK, I ran just a quick PRP test, and I also started a DC LL test (will report back if the test fails).

By the way, ROCm 4.2 improved also in terms of OpenCL support of APU Renoir (4000-series; using Gentoo with kernel 5.8.18) - now it runs `mfakto` well (self-test for GCN5 completed without error), but only after a `clinfo`-caused GPU reset. Sadly, `gpuowl` doesn't work, neither with kernels 5.10 and 5.11 (returns EE with zeroed residues; although I faintly recall that it worked with ROCm 4.1 + kernel 5.11, while spitting a lot of warnings).

Just to remind: If you have Radeon (Pro) VII, you should stay at 4.0, otherwise you will need kernel 5.13 or newer.

**Comment by preda** [comment] 2021-11-14 20:42
I'm going to close this, please re-open if still relevant.

**Closed by preda** 2021-11-14 20:42 UTC
