### ISSUE TITLE
Status of RX5700XT tests

### ISSUE THREAD

**Issue by valeriob01** [preda/gpuowl#67] opened 2019-10-19 10:41 UTC
Now that the firmware files are in place, finally the GPU is working. The Radeon RX5700XT does not work with gpuOwl for doing PRP, but works with Mfakto for doing Trial Factoring. GpuOwl doing PRP always gives error (EE lines) and after 3 consecutive errors it quits.

**Comment by selroc** [comment] 2019-11-11 13:41
I have seen that someone is asking for RX5700 benchmarks on the forum. For Trial Factoring 191M-193M from 73 to 74, it takes 20 minutes.

**Comment by preda** [comment] 2019-11-26 13:17
Thank you, you could post the benchmark results on the forum, I assume they would be easier to find there.

I don't know the cause of the always-error on RX5700, that is not expected; OTOH I have no way of testing and no plan to aquire this generation of GPUs (because they seem weak on FP64, compared to R7); closing because no action.

**Closed by preda** 2019-11-26 13:17 UTC

**Comment by valeriob01** [comment] 2019-11-26 13:55
> Thank you, you could post the benchmark results on the forum, I assume they would be easier to find there.

for some obscure reason I can't write in the forum as my account has disappeared. Can you do it please?


> I don't know the cause of the always-error on RX5700, that is not expected; OTOH I have no way of testing and no plan to aquire this generation of GPUs (because they seem weak on FP64, compared to R7); closing because no action.

I could send you my gpu for testing.

**Comment by selroc** [comment] 2019-11-27 09:05
> Thank you, you could post the benchmark results on the forum, I assume they would be easier to find there.
> 
> I don't know the cause of the always-error on RX5700, that is not expected; OTOH I have no way of testing and no plan to aquire this generation of GPUs (because they seem weak on FP64, compared to R7); closing because no action.

Ok, I know the newer generation of AMD gpus is called Arcturus, it is probably a Vega-based professional gpu, and faster than a Radeon Instinct MI60, that is the board to wait for.

**Comment by selroc** [comment] 2019-12-05 11:42
> > Thank you, you could post the benchmark results on the forum, I assume they would be easier to find there.
> > I don't know the cause of the always-error on RX5700, that is not expected; OTOH I have no way of testing and no plan to aquire this generation of GPUs (because they seem weak on FP64, compared to R7); closing because no action.
> 
> Ok, I know the newer generation of AMD gpus is called Arcturus, it is probably a Vega-based professional gpu, and faster than a Radeon Instinct MI60, that is the board to wait for.

if not willing to wait, right now one can buy the Titan V, expensive, but worth.
